#!/usr/bin/env python

import random
import string
import time

# Dump random data into a log so that it can be picked up by Telegraf

looped = True

def randomString(stringLength=10):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))

while (looped):
    time.sleep( 8 )
    f= open("/var/log/test/test1.log","a+")
    f.write('Random String,' + randomString() + ',Test\n')
    f.close()
